[Minor]: fix security audit because of rustls-webpki version (#21785)
## Which issue does this PR close?
I've realized security audit started to fail because of this 

- Closes #.

## Rationale for this change

```
error: no such command: `audit`

help: a command with a similar name exists: `add`

help: view all installed commands with `cargo --list`
help: find a package to install `audit` with `cargo search cargo-audit`
```


## What changes are included in this PR?
upgrade version

## Are these changes tested?
cargo audit passed:
```
➜ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 1052 security advisories (from /Users/buraksen/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (671 crate dependencies)
Crate:     generational-arena
Version:   0.2.9
Warning:   unmaintained
Title:     `generational-arena` is unmaintained
Date:      2024-02-11
ID:        RUSTSEC-2024-0014
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0014
Dependency tree:
generational-arena 0.2.9
└── abi_stable 0.11.3
    ├── ffi_module_loader 0.1.0
    ├── ffi_module_interface 0.1.0
    │   ├── ffi_module_loader 0.1.0
    │   └── ffi_example_table_provider 0.1.0
    ├── ffi_example_table_provider 0.1.0
    ├── datafusion-ffi 53.1.0
    │   ├── ffi_module_loader 0.1.0
    │   ├── ffi_module_interface 0.1.0
    │   └── ffi_example_table_provider 0.1.0
    └── async-ffi 0.5.0
        └── datafusion-ffi 53.1.0

Crate:     paste
Version:   1.0.15
Warning:   unmaintained
Title:     paste - no longer maintained
Date:      2024-10-07
ID:        RUSTSEC-2024-0436
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0436
Dependency tree:
paste 1.0.15
├── parquet 58.1.0
│   ├── datafusion-execution 53.1.0
│   │   ├── datafusion-wasmtest 53.1.0
│   │   ├── datafusion-spark 53.1.0
│   │   │   └── datafusion-sqllogictest 53.1.0
│   │   ├── datafusion-session 53.1.0
│   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   ├── ffi_module_loader 0.1.0
│   │   │   │   ├── ffi_module_interface 0.1.0
│   │   │   │   │   ├── ffi_module_loader 0.1.0
│   │   │   │   │   └── ffi_example_table_provider 0.1.0
│   │   │   │   └── ffi_example_table_provider 0.1.0
│   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   │   ├── datafusion-examples 53.1.0
│   │   │   │   │   └── datafusion-benchmarks 53.1.0
│   │   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   │   └── datafusion 53.1.0
│   │   │   │   │       ├── ffi_module_loader 0.1.0
│   │   │   │   │       ├── ffi_example_table_provider 0.1.0
│   │   │   │   │       ├── datafusion-wasmtest 53.1.0
│   │   │   │   │       ├── datafusion-substrait 53.1.0
│   │   │   │   │       │   └── datafusion-sqllogictest 53.1.0
│   │   │   │   │       ├── datafusion-sqllogictest 53.1.0
│   │   │   │   │       ├── datafusion-spark 53.1.0
│   │   │   │   │       ├── datafusion-proto 53.1.0
│   │   │   │   │       ├── datafusion-ffi 53.1.0
│   │   │   │   │       ├── datafusion-examples 53.1.0
│   │   │   │   │       ├── datafusion-cli 53.1.0
│   │   │   │   │       └── datafusion-benchmarks 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-datasource-json 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-datasource-csv 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-datasource-avro 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-datasource-arrow 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-datasource 53.1.0
│   │   │   │   ├── datafusion-pruning 53.1.0
│   │   │   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   │   │   └── datafusion 53.1.0
│   │   │   │   │   └── datafusion-datasource-parquet 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   │   ├── datafusion-datasource-json 53.1.0
│   │   │   │   ├── datafusion-datasource-csv 53.1.0
│   │   │   │   ├── datafusion-datasource-avro 53.1.0
│   │   │   │   ├── datafusion-datasource-arrow 53.1.0
│   │   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   │   ├── datafusion-catalog 53.1.0
│   │   │   │   │   ├── datafusion-spark 53.1.0
│   │   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   │   ├── datafusion-functions-table 53.1.0
│   │   │   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   │   │   └── datafusion 53.1.0
│   │   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   │   │   └── datafusion 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-catalog 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-proto 53.1.0
│   │   ├── datafusion-physical-plan 53.1.0
│   │   │   ├── datafusion-wasmtest 53.1.0
│   │   │   ├── datafusion-session 53.1.0
│   │   │   ├── datafusion-pruning 53.1.0
│   │   │   ├── datafusion-proto 53.1.0
│   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   ├── datafusion-functions-table 53.1.0
│   │   │   ├── datafusion-ffi 53.1.0
│   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   ├── datafusion-datasource-json 53.1.0
│   │   │   ├── datafusion-datasource-csv 53.1.0
│   │   │   ├── datafusion-datasource-avro 53.1.0
│   │   │   ├── datafusion-datasource-arrow 53.1.0
│   │   │   ├── datafusion-datasource 53.1.0
│   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   ├── datafusion-catalog 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-physical-optimizer 53.1.0
│   │   ├── datafusion-functions-nested 53.1.0
│   │   │   ├── datafusion-sql 53.1.0
│   │   │   │   ├── datafusion-wasmtest 53.1.0
│   │   │   │   ├── datafusion-optimizer 53.1.0
│   │   │   │   │   ├── datafusion-wasmtest 53.1.0
│   │   │   │   │   └── datafusion 53.1.0
│   │   │   │   ├── datafusion-examples 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-spark 53.1.0
│   │   │   ├── datafusion-pruning 53.1.0
│   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-functions-aggregate 53.1.0
│   │   │   ├── datafusion-substrait 53.1.0
│   │   │   ├── datafusion-sql 53.1.0
│   │   │   ├── datafusion-spark 53.1.0
│   │   │   ├── datafusion-proto 53.1.0
│   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   ├── datafusion-optimizer 53.1.0
│   │   │   ├── datafusion-functions-nested 53.1.0
│   │   │   ├── datafusion-ffi 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-functions 53.1.0
│   │   │   ├── datafusion-sql 53.1.0
│   │   │   ├── datafusion-spark 53.1.0
│   │   │   ├── datafusion-proto 53.1.0
│   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   ├── datafusion-physical-expr-adapter 53.1.0
│   │   │   │   ├── datafusion-examples 53.1.0
│   │   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   │   ├── datafusion-datasource-avro 53.1.0
│   │   │   │   ├── datafusion-datasource 53.1.0
│   │   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-physical-expr 53.1.0
│   │   │   │   ├── datafusion-pruning 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   │   ├── datafusion-physical-expr-adapter 53.1.0
│   │   │   │   ├── datafusion-optimizer 53.1.0
│   │   │   │   ├── datafusion-functions-window 53.1.0
│   │   │   │   │   ├── datafusion-sql 53.1.0
│   │   │   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   │   │   ├── datafusion-optimizer 53.1.0
│   │   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   │   └── datafusion 53.1.0
│   │   │   │   ├── datafusion-functions-aggregate 53.1.0
│   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   │   ├── datafusion-datasource 53.1.0
│   │   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   │   ├── datafusion-catalog 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-functions-nested 53.1.0
│   │   │   ├── datafusion-ffi 53.1.0
│   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-ffi 53.1.0
│   │   ├── datafusion-datasource-parquet 53.1.0
│   │   ├── datafusion-datasource-json 53.1.0
│   │   ├── datafusion-datasource-csv 53.1.0
│   │   ├── datafusion-datasource-arrow 53.1.0
│   │   ├── datafusion-datasource 53.1.0
│   │   ├── datafusion-catalog-listing 53.1.0
│   │   ├── datafusion-catalog 53.1.0
│   │   └── datafusion 53.1.0
│   ├── datafusion-datasource-parquet 53.1.0
│   ├── datafusion-common 53.1.0
│   │   ├── test-utils 0.1.0
│   │   │   ├── datafusion-examples 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-wasmtest 53.1.0
│   │   ├── datafusion-sql 53.1.0
│   │   ├── datafusion-spark 53.1.0
│   │   ├── datafusion-session 53.1.0
│   │   ├── datafusion-pruning 53.1.0
│   │   ├── datafusion-proto-common 53.1.0
│   │   │   ├── datafusion-proto 53.1.0
│   │   │   └── datafusion-ffi 53.1.0
│   │   ├── datafusion-proto 53.1.0
│   │   ├── datafusion-physical-plan 53.1.0
│   │   ├── datafusion-physical-optimizer 53.1.0
│   │   ├── datafusion-physical-expr-common 53.1.0
│   │   │   ├── datafusion-pruning 53.1.0
│   │   │   ├── datafusion-proto 53.1.0
│   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   ├── datafusion-physical-expr-adapter 53.1.0
│   │   │   ├── datafusion-physical-expr 53.1.0
│   │   │   ├── datafusion-functions-window-common 53.1.0
│   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   │   ├── datafusion-optimizer 53.1.0
│   │   │   │   ├── datafusion-functions-window 53.1.0
│   │   │   │   ├── datafusion-expr 53.1.0
│   │   │   │   │   ├── datafusion-wasmtest 53.1.0
│   │   │   │   │   ├── datafusion-sql 53.1.0
│   │   │   │   │   ├── datafusion-spark 53.1.0
│   │   │   │   │   ├── datafusion-session 53.1.0
│   │   │   │   │   ├── datafusion-pruning 53.1.0
│   │   │   │   │   ├── datafusion-proto 53.1.0
│   │   │   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   │   │   ├── datafusion-physical-expr-adapter 53.1.0
│   │   │   │   │   ├── datafusion-physical-expr 53.1.0
│   │   │   │   │   ├── datafusion-optimizer 53.1.0
│   │   │   │   │   ├── datafusion-functions-window 53.1.0
│   │   │   │   │   ├── datafusion-functions-table 53.1.0
│   │   │   │   │   ├── datafusion-functions-nested 53.1.0
│   │   │   │   │   ├── datafusion-functions-aggregate 53.1.0
│   │   │   │   │   ├── datafusion-functions 53.1.0
│   │   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   │   ├── datafusion-execution 53.1.0
│   │   │   │   │   ├── datafusion-examples 53.1.0
│   │   │   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   │   │   ├── datafusion-datasource-json 53.1.0
│   │   │   │   │   ├── datafusion-datasource-csv 53.1.0
│   │   │   │   │   ├── datafusion-datasource-arrow 53.1.0
│   │   │   │   │   ├── datafusion-datasource 53.1.0
│   │   │   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   │   │   ├── datafusion-catalog 53.1.0
│   │   │   │   │   └── datafusion 53.1.0
│   │   │   │   └── datafusion 53.1.0
│   │   │   ├── datafusion-functions-window 53.1.0
│   │   │   ├── datafusion-functions-nested 53.1.0
│   │   │   ├── datafusion-functions-aggregate-common 53.1.0
│   │   │   │   ├── datafusion-physical-plan 53.1.0
│   │   │   │   ├── datafusion-physical-expr 53.1.0
│   │   │   │   ├── datafusion-functions-nested 53.1.0
│   │   │   │   ├── datafusion-functions-aggregate 53.1.0
│   │   │   │   ├── datafusion-ffi 53.1.0
│   │   │   │   ├── datafusion-expr 53.1.0
│   │   │   │   └── datafusion-datasource-parquet 53.1.0
│   │   │   ├── datafusion-functions-aggregate 53.1.0
│   │   │   ├── datafusion-ffi 53.1.0
│   │   │   ├── datafusion-expr 53.1.0
│   │   │   ├── datafusion-execution 53.1.0
│   │   │   ├── datafusion-datasource-parquet 53.1.0
│   │   │   ├── datafusion-datasource-json 53.1.0
│   │   │   ├── datafusion-datasource-csv 53.1.0
│   │   │   ├── datafusion-datasource-arrow 53.1.0
│   │   │   ├── datafusion-datasource 53.1.0
│   │   │   ├── datafusion-catalog-listing 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-physical-expr-adapter 53.1.0
│   │   ├── datafusion-physical-expr 53.1.0
│   │   ├── datafusion-optimizer 53.1.0
│   │   ├── datafusion-functions-window-common 53.1.0
│   │   ├── datafusion-functions-window 53.1.0
│   │   ├── datafusion-functions-table 53.1.0
│   │   ├── datafusion-functions-nested 53.1.0
│   │   ├── datafusion-functions-aggregate-common 53.1.0
│   │   ├── datafusion-functions-aggregate 53.1.0
│   │   ├── datafusion-functions 53.1.0
│   │   ├── datafusion-ffi 53.1.0
│   │   ├── datafusion-expr-common 53.1.0
│   │   │   ├── datafusion-pruning 53.1.0
│   │   │   ├── datafusion-physical-optimizer 53.1.0
│   │   │   ├── datafusion-physical-expr-common 53.1.0
│   │   │   ├── datafusion-physical-expr 53.1.0
│   │   │   ├── datafusion-optimizer 53.1.0
│   │   │   ├── datafusion-functions-nested 53.1.0
│   │   │   ├── datafusion-functions-aggregate-common 53.1.0
│   │   │   ├── datafusion-functions 53.1.0
│   │   │   ├── datafusion-expr 53.1.0
│   │   │   └── datafusion 53.1.0
│   │   ├── datafusion-expr 53.1.0
│   │   ├── datafusion-execution 53.1.0
│   │   ├── datafusion-examples 53.1.0
│   │   ├── datafusion-datasource-parquet 53.1.0
│   │   ├── datafusion-datasource-json 53.1.0
│   │   ├── datafusion-datasource-csv 53.1.0
│   │   ├── datafusion-datasource-avro 53.1.0
│   │   ├── datafusion-datasource-arrow 53.1.0
│   │   ├── datafusion-datasource 53.1.0
│   │   ├── datafusion-cli 53.1.0
│   │   ├── datafusion-catalog-listing 53.1.0
│   │   ├── datafusion-catalog 53.1.0
│   │   ├── datafusion-benchmarks 53.1.0
│   │   └── datafusion 53.1.0
│   ├── datafusion-cli 53.1.0
│   ├── datafusion-benchmarks 53.1.0
│   └── datafusion 53.1.0
├── arrow-flight 58.1.0
│   └── datafusion-examples 53.1.0
└── abi_stable 0.11.3
    ├── ffi_module_loader 0.1.0
    ├── ffi_module_interface 0.1.0
    ├── ffi_example_table_provider 0.1.0
    ├── datafusion-ffi 53.1.0
    └── async-ffi 0.5.0
        └── datafusion-ffi 53.1.0

warning: 2 allowed warnings found
```

## Are there any user-facing changes?
no